# Generated by Django 5.1.6 on 2025-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('trading', 'Trading Volume'), ('revenue', 'Revenue Tracking'), ('profit_loss', 'Profit/Loss')], max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='analytics_reports/')),
            ],
        ),
    ]
